export const CARD_DATA_SET = [
  {
    image: require('@asset/projectImage.png'),
    title: 'Windmill out of toothpaste box',
    desc: 'This is a test description containing description of a project',
    AuthorName: 'Alice Ndeh',
    role: 'CREATOR',
    avater: require('@asset/188.jpg'),
    timeline: '1 YEAR AGO',
    NOV: 22,
    messages: 12,
    clap: 0,
  },
  {
    image: require('@asset/download.png'),
    title: 'Windmill out of toothpaste box',
    desc: 'This is a test description containing description of a project',
    AuthorName: 'Alice Ndeh',
    role: 'CREATOR',
    avater: require('@asset/65.jpg'),
    timeline: '1 YEAR AGO',
    NOV: 27,
    clap: 0,
    messages: 42,
  },
  {
    image: require('@asset/projectImage.png'),
    title: 'Windmill out of toothpaste box',
    desc: 'This is a test description containing description of a project',
    AuthorName: 'Alice Ndeh',
    role: 'CREATOR',
    avater: require('@asset/R.jpg'),
    timeline: '1 YEAR AGO',
    NOV: 22,
    clap: 0,
    messages: 12,
  },
  {
    image: require('@asset/download.png'),
    title: 'Windmill out of toothpaste box',
    desc: 'This is a test description containing description of a project',
    AuthorName: 'Alice Ndeh',
    role: 'CREATOR',
    avater: require('@asset/128.jpg'),
    timeline: '1 YEAR AGO',
    NOV: 27,
    clap: 0,
    messages: 42,
  },
];
